const { command } = require("./redis");
const INDEX_KEY="jcv3:people:index:v1", DETAIL_PREFIX="jcv3:people:detail:v1:";
const pad=n=>String(n).padStart(3,"0"), clean=(v,max=5000)=>String(v??"").replace(/\u0000/g,"").trim().slice(0,max), detailKey=id=>`${DETAIL_PREFIX}${id}`;
const career=v=>clean(v,20000).split(/\r?\n|<br\s*\/?>|ㆍ|•/i).map(x=>x.replace(/^[\s\-·]+/,"").trim()).filter(Boolean).slice(0,40);
const committees=r=>clean(r.CMITS||r.CMIT_NM||"",3000).split(/[,/]/).map(x=>x.trim()).filter(Boolean).slice(0,12);
async function getPeopleIndex(){const raw=await command(["GET",INDEX_KEY]);try{return raw?JSON.parse(raw):{updatedAt:"",source:"",items:[]}}catch{return{updatedAt:"",source:"",items:[]}}}
async function getPersonDetail(id){const raw=await command(["GET",detailKey(String(id||""))]);try{return raw?JSON.parse(raw):null}catch{return null}}
async function setIndex(data){await command(["SET",INDEX_KEY,JSON.stringify(data)])}
async function setDetails(items){for(let i=0;i<items.length;i+=35){const args=["MSET"];for(const x of items.slice(i,i+35))args.push(detailKey(x.id),JSON.stringify(x));await command(args)}}
function normalize(r,id){const cs=committees(r),district=clean(r.ORIG_NM,120),party=clean(r.POLY_NM,80),officialCode=clean(r.MONA_CD||r.NAAS_CD,80);return{id,type:"assembly",roleLabel:"국회의원",connected:true,officialCode,name:clean(r.HG_NM,80),hanjaName:clean(r.HJ_NM,80),englishName:clean(r.ENG_NM,120),party,jurisdiction:district,electionType:clean(r.ELECT_GBN_NM,80),seniority:clean(r.REELE_GBN_NM,80),gender:clean(r.SEX_GBN_NM,20),birthDate:clean(r.BTH_DATE||r.BIRDY_DT,30),education:clean(r.SCHL_NM||r.EDU_HST,500),committees:cs,contact:{phone:clean(r.TEL_NO,80),email:clean(r.E_MAIL,160),homepage:clean(r.HOMEPAGE,500)},term:{assembly:22,start:"2024-05-30",end:"2028-05-29"},election:{assembly:22,district,electedType:clean(r.ELECT_GBN_NM,80),seniority:clean(r.REELE_GBN_NM,80),voteRate:null,history:[]},career:career(r.BRF_HST),activities:{committees:cs,representativeBills:[],plenaryAttendance:null,achievements:[]},pledges:[],policies:[],photo:"",source:{provider:"대한민국 국회 열린국회정보",dataset:"국회의원 인적사항",endpoint:"nwvrqwxyaytdsfvhu",officialCode,syncedAt:new Date().toISOString()}}}
function allocate(rows,prev){const byCode=new Map(),occupied=new Set();for(const x of prev.items||[])if(x.type==="assembly"&&x.officialCode){byCode.set(x.officialCode,x.id);occupied.add(x.id)}const free=[];for(let i=1;i<=300;i++){const id=`assembly-${pad(i)}`;if(!occupied.has(id))free.push(id)}let c=0;return rows.map(r=>({r,id:byCode.get(clean(r.MONA_CD||r.NAAS_CD,80))||free[c++]})).filter(x=>x.id)}
async function fetchRows(){const key=clean(process.env.OPEN_ASSEMBLY_API_KEY,1000);if(!key){const e=new Error("OPEN_ASSEMBLY_API_KEY_MISSING");e.code="OPEN_ASSEMBLY_API_KEY_MISSING";throw e}const u=new URL("https://open.assembly.go.kr/portal/openapi/nwvrqwxyaytdsfvhu");u.searchParams.set("KEY",key);u.searchParams.set("Type","json");u.searchParams.set("pIndex","1");u.searchParams.set("pSize","1000");const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(u,{headers:{Accept:"application/json"},signal:ctl.signal});if(!r.ok){const e=new Error("OPEN_ASSEMBLY_REQUEST_FAILED");e.code="OPEN_ASSEMBLY_REQUEST_FAILED";throw e}const b=await r.json();const root=Object.keys(b).find(k=>Array.isArray(b[k]));const blocks=root?b[root]:[];const rows=blocks?.find(x=>Array.isArray(x.row))?.row||[];if(!rows.length){const e=new Error("OPEN_ASSEMBLY_EMPTY");e.code="OPEN_ASSEMBLY_EMPTY";throw e}return rows.filter(x=>clean(x.HG_NM,80))}finally{clearTimeout(t)}}
async function syncAssemblyPeople(){const rows=await fetchRows(),prev=await getPeopleIndex(),allocated=allocate(rows,prev),details=allocated.map(x=>normalize(x.r,x.id)),map=new Map(details.map(x=>[x.id,x])),assembly=[];for(let i=1;i<=300;i++){const id=`assembly-${pad(i)}`,d=map.get(id);assembly.push(d?{id,type:"assembly",slot:i,roleLabel:"국회의원",connected:true,officialCode:d.officialCode,name:d.name,party:d.party,jurisdiction:d.jurisdiction,seniority:d.seniority,electionType:d.electionType}:{id,type:"assembly",slot:i,roleLabel:"국회의원",connected:false})}const rest=(prev.items||[]).filter(x=>x.type!=="assembly"),index={version:1,updatedAt:new Date().toISOString(),source:"대한민국 국회 열린국회정보 · 국회의원 인적사항",counts:{assemblyConnected:details.length,assemblySlots:300,metropolitanConnected:rest.filter(x=>x.type==="metropolitan"&&x.connected).length,basicConnected:rest.filter(x=>x.type==="basic"&&x.connected).length},items:[...assembly,...rest]};await setDetails(details);await setIndex(index);return{index,connected:details.length}}
module.exports={getPeopleIndex,getPersonDetail,syncAssemblyPeople};
